import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { User } from "lucide-react";
User



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const items = [
 
  { name: "about", url: "/about" },
  { name: "services", url: "/services" },
  { name: "products", url: "/products" },
  { name: "blog", url: "/blog" },
  { name: "contact", url: "/contact" },
];

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
          <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <NavBar items={items}/>
       
        {children}
      </body>
    </html>
  );
}
